name: ColonyNet
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - scikit-image
  - opencv
  - pyside6
  - pyinstaller
  - scikit-learn
  - medpy
  - fastapi
  - uvicorn
  - python-multipart
  - tqdm